### ISSUE TITLE
Need OLexp-data to test the sayIfLearned function

### ISSUE THREAD

**Issue by WanzhuoShi** [Wenlab/ABLITZER#13]
I have just modified the sayIfLearned function, but I have no OLexp-Dataset to test it. Could you please upload a new yaml file to the server? Thanks a lot.
@young24

**Comment by WanzhuoShi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [modify ABLITZER](https://trello.com/c/AMqKppo3/24-modify-ablitzer)

**Comment by young24** [comment]
I uploaded the data "20180504_10dpf_GCaMP_OL_pureBlack.mat" to the server. You can load the file by simply opening it in MATLAB. 
@WanzhuoShi

**Comment by young24** [comment]
In this file, there are paired experiments, you can find some learned fish among them.

**Comment by WanzhuoShi** [comment]
Great! It works. Thank you.
