### ISSUE TITLE
Convert code from Matlab to C++

### ISSUE THREAD

**Issue by danyang123** [Wenlab/ABLITZER#23]
I have push code to Branch " LTS-ldy ", can you transform the code from Matlab to C++? Thanks . @CrickCrick

**Comment by CrickCrick** [comment]
OK

**Comment by danyang123** [comment]
Can you write the C++ code that returns only an angle so that we can start experimenting as soon as possible? The code that returns multiple angles, I think we can do it later as an optimization.
@CrickCrick
